### PR TITLE
update CADD input file names

### PR DESCRIPTION
**Pull request by KoalaQin**
I renamed all the files to have consistent info and format but I forgot to update the code, and I added the new variants from v4 genomes.

### CODE REVIEW

**Review by mike-w-wilson — APPROVED** [review]
LGTM

**Comment by KoalaQin** [comment]
I will put this one on hold, because I just realized that I have to rerun CADD for the new indels from added HGDP/TGP samples.

**Comment by KoalaQin** [comment]
@mike-w-wilson could you review it before I run CADD?

**Review by jkgoodrich — APPROVED** [review]
I took a look and it LGTM!

**Pull request merged**
