### PR TITLE
change overwrite in checkpoint

### PR DESCRIPTION
**Pull request by KoalaQin**

### CODE REVIEW

**Review by mike-w-wilson — COMMENTED** [review]
I think you need to pass overwrite to the revel function itself. Or can you access args from here?

**Comment by KoalaQin** [comment]
Yeah, I used this: 
`hailctl dataproc submit qh-insilico gnomad_qc/v4/annotations/insilico_predictors.py --revel --overwrite`
but there was a copy of that file already.

**Comment by mike-w-wilson** [comment]
Yes, I shouldnt have approved the last PR, I missed that the `_read_if_exists` was changed to an `overwrite`. `overwrite= not arg.overwrite` should not be a thing. My question is can you access the args array from inside the revel function since you are not passing it?

**Comment by KoalaQin** [comment]
I could access the args, the run was successful, but the merging checks didn't pass: https://github.com/broadinstitute/gnomad_qc/actions/runs/6251213810/job/16971846070
What do we do?

**Comment by mike-w-wilson** [comment]
You could try rerunning the job

**Comment by KoalaQin** [comment]
Is it okay to use overwrite instead of _read_if_exists? I can also change it back to:
`_read_if_exists=not args.overwrite`?

**Comment by mike-w-wilson** [comment]
It should be overwrite. If the job is fast though do you even need the checkpoint?

**Comment by KoalaQin** [comment]
Maybe not, I just don't like Hail output temporary files in logger.

**Pull request merged**
