### PR TITLE
change CURRENT RELEASE to 3.1.4

### PR DESCRIPTION
**Pull request by KoalaQin**
change CURRENT RELEASE to 3.1.4, add 3.1.3 and 3.1.4 to RELEASES. 
Not sure if this will influence other codes.

### CODE REVIEW

**Review by jkgoodrich — CHANGES_REQUESTED** [review]
Just a small change

**Comment by KoalaQin** [comment]
> 
Actually KC wants to discuss this, if we put a note on each release in the code on the major changes or we give a link to the blogpost.

**Comment by jkgoodrich** [comment]
I think we need this specific note in the code no matter what. You can make another ticket and accompanying PR for deciding on and implementing any additional documentation that should be added to describe the release changes.

**Comment by jkgoodrich** [comment]
I went through the code where `CURRENT_RELEASE` is used and found some errors I had made in the initial change. I'm going to put in a PR on top of this branch for those changes.

**Comment by KoalaQin** [comment]
> 

I was worried about that. Could you show me how you detect errors when change like this happen?

**Review by jkgoodrich — APPROVED** [review]

**Pull request merged**
