### PR TITLE
Mw/custom global select

### PR DESCRIPTION
**Pull request by mike-w-wilson**
This adds custom global select functionality to the release code. This allows us to drop fields from global structs or make any other desired modifications, similar to custom_select_fields.

### CODE REVIEW

**Review by jkgoodrich — APPROVED** [review]
LGTM, only question is, should we do something about the temp output path? Or add a TODO if it's not worth doing now

    output_path = (
        f"{qc_temp_prefix()}release/gnomad.{data_type}.sites.test.updated_102023.ht"
        if args.test
        else release_sites(data_type=data_type).path
    )

**Comment by KoalaQin** [comment]
Maybe we can put a current date in the test output name?

**Review by KoalaQin — COMMENTED** [review]
Maybe we can put a current date in the test output name? I mean use `datetime`?

**Comment by mike-w-wilson** [comment]
@jkgoodrich @KoalaQin , Yeah the temp path was something I had in the back of my mind, good chance we'll rerun this so I added in datetime (thanks for the suggestion Qin) and a datatype to the basic qc temp path.

**Review by KoalaQin — APPROVED** [review]
LGTM!

**Pull request merged**
