### PR TITLE
Pass data_type to included datasets path function

### PR DESCRIPTION
**Pull request by mike-w-wilson**
We dont have an included datasets json for v4.0 genomes. This will fix that moving forward.  We ran exomes last so the existing datasets file is correct.

### CODE REVIEW

**Review by KoalaQin — CHANGES_REQUESTED** [review]
I have 2 questions: 
1. Can you get json file without rerun the whole thing?
2. There is an error here: 
https://github.com/broadinstitute/gnomad_qc/blob/1c1dfbc44d54379ac16b71af603c67a990fbfb4b/gnomad_qc/v4/resources/release.py#L379C1-L379C1
You might change this to: 
```
        f"{_release_root(release_version, test=test, data_type=data_type, extension='json')}/gnomad.{data_type}.v{release_version}.included_datasets.json"
```

**Comment by mike-w-wilson** [comment]
When you say copied and replaced, was this just a text change? Or did you confirm the paths were accurate? The v4 release pulls from v3.1 for genomes: https://github.com/broadinstitute/gnomad_qc/blob/1c1dfbc44d54379ac16b71af603c67a990fbfb4b/gnomad_qc/v4/create_release/create_release_sites_ht.py#L222

**Comment by KoalaQin** [comment]
Yes, text change, I copied from gs://gnomad/release/4.0/json/exomes/gnomad.exomes.v4.0.included_datasets.json to local and edited this file, then copied it back to gs://gnomad/release/4.0/json/genomes/gnomad.genomes.v4.0.included_datasets.json
You can have a look at both. I didn't replace the exome one. 
That's how I got info HT path.

**Comment by mike-w-wilson** [comment]
@KoalaQin , are there any other changes you'd like to see?

**Review by KoalaQin — APPROVED** [review]
LGTM! I just wanted you to double check the genome json file.

**Comment by mike-w-wilson** [comment]
Thank you -- I also documented the genome included datasets json file creation [here](https://app.zenhub.com/workspaces/gnomad-5f4d127ea61afc001d6be50b/issues/gh/broadinstitute/gnomad_production/1335).

**Pull request merged**
